# Generated by Django 2.1.7 on 2019-03-18 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170719_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbOngoingCreationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='running_platform_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pb_ongoing_task',
            },
        ),
    ]
