# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pbavailableplaforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsubdomains',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
