# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pbconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsubdomains',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
