# Generated by Django 2.1.7 on 2019-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170726_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbconfig',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
