# Generated by Django 2.1.7 on 2019-04-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pbavailableplaforms_installation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsubdomains',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='platform_subs', to='main.PbAvailablePlaforms'),
        ),
    ]
