# Generated by Django 2.1.7 on 2019-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pbsubdomains_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsubdomains',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
